name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t 3ds
    - name: Make export folder
      run: mkdir export
    - name: Build the 3DS CIA
      run: docker run --rm -it --volume $PWD/export:/home/usr/export 3ds
